---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters.df = read_csv("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/FAS_litters.csv")
litters.df = janitor::clean_names(litters.df)
```

## 'Select'

Choose some columns and not others.

```{r}
select(litters.df, group, gd0_weight)
```


```{r}
select(litters.df, group, gd0_weight:gd_of_birth)
```


```{r}
select(litters.df, -litter_number)
```

Renaming columns...

```{r}
select(litters.df, GROUP = group , LiTTer_Number = litter_number)
```

```{r}
rename(litters.df, GROUP = group , LiTTer_Number = litter_number)
```

Select helpers

```{r}
select(litters.df, starts_with("gd"))
```

```{r}
select(litters.df, litter_number, everything())
```

```{r}
relocate(litters.df, group)
```


## 'Filter'

```{r}
filter(litters.df, gd0_weight < 22)
```

```{r}
filter(litters.df, gd0_weight >= 22)
```

```{r}
filter(litters.df, gd_of_birth == 20)

```

```{r}
filter(litters.df, !(gd_of_birth == 20))
```

```{r}
filter(litters.df, gd_of_birth != 20)
```

```{r}
filter(litters.df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters.df, group == "Mod8")
```

```{r}
filter(litters.df, group %in% c("Con7", "Mod7"))
```

## 'Mutate'

```{r}
mutate(
  litters.df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )

```

## 'Arrange'

```{r}
arrange(litters.df, pups_born_alive)
```

## '%>%'

```{r}
litters.data.row = read_csv("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/FAS_litters.csv")
litters.clean.name = janitor::clean_names(litters.data.row)
litters.data.selected = select(litters.clean.name , -pups_survive)
litters.mutated = mutate(litters.data.selected, wt_gain = gd18_weight - gd0_weight)
litters.without.missing = drop_na(litters.mutated, gd0_weight)
```

USE THE PIPE OPERATOR INSTEAD 

```{r}
litters.df =
   read_csv("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>%
  drop_na(gd0_weight)
  
```


