---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data 

Read in the litters dataset.

```{r}
litters.df = read_csv("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/FAS_litters.csv")
litters.df = janitor::clean_names(litters.df)
```


## Take a look at data

```{r}
litters.df
```

```{r}
head(litters.df)
tail(litters.df)
```

```{r}
skimr::skim(litters.df)
```

## Options to read_csv

check out "?read_csv()" for more info.



# Other file formats

Read in excel file

```{r}
mlb.df = read_excel("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/mlb11.xlsx", range = "A1:F7")
mlb.df
```

Read in a SAS file 

```{r}
pulse.df = read_sas("/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/public_pulse_data.sas7bdat")
pulse.df

```

## Exporting Data

Export the mlb sub-table.

```{r}
write_csv(mlb.df, "/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Data Wrangling/data_wrangling_1/data/mlb_subtable.csv")
```


